title: All good :-)
author: Someone
email: someone@somewhere.com
description: > # this means to ignore newlines until "baseurl:"
  I would like to describe something, but I have no idea 
  what i could describe, because there is nothing special 
  that isn't explained. If you need information about 
  GitHub, check the site.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
